version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    ports:
    - 4000:4000
    volumes:
    - ./:/usr/src/app:delegated,ro
    tty: true
    command: jekyll serve -d /_site --watch --force_polling -H 0.0.0.0 -P 4000 --drafts
